# Generated by Django 2.1.2 on 2018-10-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0004_auto_20181018_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='users.User'),
        ),
    ]
