# Generated by Django 2.1.2 on 2018-10-20 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20181019_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='up_votes_list',
            field=models.ManyToManyField(related_name='vote_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
