# Generated by Django 2.1.2 on 2018-10-20 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_up_votes_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='up_votes_list',
            field=models.ManyToManyField(blank=True, related_name='vote_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
