# Generated by Django 2.1.2 on 2018-10-22 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20181020_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='post',
            name='down_votes_list',
            field=models.ManyToManyField(blank=True, related_name='down_votes_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
