# Generated by Django 2.1.2 on 2018-10-22 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20181022_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='down_votes_list',
            field=models.ManyToManyField(blank=True, related_name='comment_down_vote_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_votes_list',
            field=models.ManyToManyField(blank=True, related_name='comment_vote_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
