# Generated by Django 2.1.2 on 2018-10-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20181020_1903'),
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='random_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Post'),
        ),
    ]
