# Generated by Django 2.1.2 on 2018-10-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinfo_random_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
