# Generated by Django 2.1.2 on 2018-10-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userinfo_posts_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='posts_available',
        ),
    ]
