# Generated by Django 2.1.2 on 2018-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userinfo_posts_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profilePictures/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='xp',
            field=models.IntegerField(default=100),
        ),
    ]
